---
- hosts: all
  become: yes
  tasks:
    - name: install at
      yum: 
        name:  at
        state: present
    - name: Enable service atd
      service:
        name: atd
        enabled: yes
        state: started
    - name: Copy the ban_ip.sh file to the remote server
      copy:
        src: ban_ip.sh
        dest: /opt
        force: yes
        backup: yes
    - name: Modify the threshold
      lineinfile:
        path: /opt/ban_ip.sh
        regexp: "^vpt="
        line: vpt={{ vpt }}
    - name: Modify the expire time
      lineinfile:
        path: /opt/ban_ip.sh
        regexp: "^expire_time="
        line: expire_time={{ expire_time }}
    - name: Creates a cron
      cron:
        name: banIP
        minute: "*"
        user: root
        job: "/bin/bash /opt/ban_ip.sh"
        state: "{{ state }}"

